"""
export_weights.py — Convert trained ProfitPolicyNet checkpoint to SystemVerilog.

Usage:
    python export_weights.py --checkpoint profit_nn_out/model_best_v1_profitable.pth.tar
    python export_weights.py --checkpoint profit_nn_out/model_best_v1_profitable.pth.tar --scale 256 --bits 8
    python export_weights.py --checkpoint profit_nn_out/model_best_v1_profitable.pth.tar --out policy_weights.sv

What it does:
    1. Loads the checkpoint and extracts all weight/bias tensors
    2. Quantizes floats to fixed-point integers (default: 16-bit, scale=256 = 8 fractional bits)
    3. Prints a SystemVerilog .sv file with localparam arrays for every layer
    4. Prints a Python inference snippet you can use to verify the quantized model

Network architecture (single MLP):
    Input:  9 features (deviation, spread, mid_delta, ema_delta,
                        position_norm, regime_norm, dev_spread_ratio,
                        entry_price_delta, holding_time_norm)
    Layer0: Linear(9  -> 128) + ReLU
    Layer1: Linear(128-> 128) + ReLU
    Layer2: Linear(128->  64) + ReLU
    Layer3: Linear(64 ->   3) -> logits [HOLD, BUY, SELL]

Fixed-point format:
    Default: signed 16-bit, scale factor = 256 (Q8.8 effectively)
    You can override with --bits and --scale flags.
    All arithmetic in RTL should use the same scale factor.
"""

from __future__ import annotations

import argparse
import os
import sys
from typing import Optional

import numpy as np


def load_state_dict(checkpoint_path: str) -> dict:
    try:
        import torch
        ckpt = torch.load(checkpoint_path, map_location="cpu")
        state = ckpt["state_dict"] if "state_dict" in ckpt else ckpt
        return {k: v.numpy() for k, v in state.items()}
    except ImportError:
        print("ERROR: PyTorch not installed. Run: pip install torch", file=sys.stderr)
        sys.exit(1)
    except FileNotFoundError:
        print(f"ERROR: Checkpoint not found: {checkpoint_path}", file=sys.stderr)
        sys.exit(1)


def quantize(arr: np.ndarray, scale: int, bits: int) -> np.ndarray:
    """Quantize float array to signed fixed-point integer."""
    max_val = (1 << (bits - 1)) - 1
    min_val = -(1 << (bits - 1))
    quantized = np.round(arr * scale).astype(np.int64)
    clipped = np.clip(quantized, min_val, max_val)
    n_clipped = np.sum(np.abs(quantized) > max_val)
    if n_clipped > 0:
        print(f"  WARNING: {n_clipped}/{arr.size} values clipped — consider reducing --scale", file=sys.stderr)
    return clipped.astype(np.int32)


def format_sv_array(name: str, values: np.ndarray, bits: int) -> str:
    """Format a flat array as a SystemVerilog localparam."""
    hex_width = (bits + 3) // 4
    sign = "s" if bits > 1 else ""
    lines = []
    lines.append(f"localparam logic signed [{bits-1}:0] {name} [0:{len(values)-1}] = '{{")
    # 8 values per line
    chunks = [values[i:i+8] for i in range(0, len(values), 8)]
    for ci, chunk in enumerate(chunks):
        vals = ", ".join(f"{bits}'h{v & ((1 << bits) - 1):0{hex_width}X}" for v in chunk)
        comma = "," if ci < len(chunks) - 1 else ""
        lines.append(f"    {vals}{comma}")
    lines.append("};")
    return "\n".join(lines)


def format_sv_scalar(name: str, value: int, bits: int) -> str:
    hex_width = (bits + 3) // 4
    return f"localparam logic signed [{bits-1}:0] {name} = {bits}'h{value & ((1 << bits) - 1):0{hex_width}X};"


def generate_sv(state: dict, scale: int, bits: int, module_name: str) -> str:
    """Generate the full SystemVerilog package with all weight localparams."""

    # Map expected layer names
    layer_map = {
        "net.0": ("L0", 9,   128),   # first linear
        "net.2": ("L1", 128, 128),   # second linear
        "net.4": ("L2", 128, 64),    # third linear
        "net.6": ("L3", 64,  3),     # output linear
    }

    lines = []
    lines.append(f"// Auto-generated by export_weights.py")
    lines.append(f"// Checkpoint: see --checkpoint argument")
    lines.append(f"// Scale factor: {scale} (multiply floats by {scale} to get integers)")
    lines.append(f"// Bit width: {bits}-bit signed")
    lines.append(f"// Network: 9 -> 128 -> 128 -> 64 -> 3 (HOLD/BUY/SELL)")
    lines.append(f"// Features: [deviation, spread, mid_delta, ema_delta, position_norm,")
    lines.append(f"//            regime_norm, dev_spread_ratio, entry_price_delta, holding_time_norm]")
    lines.append(f"// Actions:  0=HOLD, 1=BUY, 2=SELL")
    lines.append(f"")
    lines.append(f"package {module_name}_pkg;")
    lines.append(f"")
    lines.append(f"  // Scale factor — divide accumulator by this after each MAC")
    lines.append(f"  localparam int WEIGHT_SCALE = {scale};")
    lines.append(f"  localparam int WEIGHT_BITS  = {bits};")
    lines.append(f"  localparam int INPUT_DIM    = 9;")
    lines.append(f"  localparam int HIDDEN0_DIM  = 128;")
    lines.append(f"  localparam int HIDDEN1_DIM  = 128;")
    lines.append(f"  localparam int HIDDEN2_DIM  = 64;")
    lines.append(f"  localparam int OUTPUT_DIM   = 3;")
    lines.append(f"  // Actions")
    lines.append(f"  localparam int ACTION_HOLD  = 0;")
    lines.append(f"  localparam int ACTION_BUY   = 1;")
    lines.append(f"  localparam int ACTION_SELL  = 2;")
    lines.append(f"")

    found_layers = []
    for prefix, (label, in_dim, out_dim) in layer_map.items():
        w_key = f"{prefix}.weight"
        b_key = f"{prefix}.bias"
        if w_key not in state:
            print(f"  WARNING: {w_key} not found in checkpoint", file=sys.stderr)
            continue

        w = state[w_key]   # shape (out_dim, in_dim)
        b = state[b_key]   # shape (out_dim,)

        w_q = quantize(w, scale, bits)
        b_q = quantize(b, scale, bits)

        lines.append(f"  // {label}: Linear({in_dim} -> {out_dim})")
        lines.append(f"  // Weight matrix: [{out_dim}][{in_dim}] stored row-major")
        lines.append(f"  // w[row*{in_dim} + col] = weight from input col to output row")

        # weights flattened row-major
        w_flat = w_q.flatten()
        lines.append("  " + format_sv_array(f"{label}_W", w_flat, bits).replace("\n", "\n  "))
        lines.append("")
        lines.append("  " + format_sv_array(f"{label}_B", b_q.flatten(), bits).replace("\n", "\n  "))
        lines.append("")
        found_layers.append(label)

    lines.append(f"endpackage : {module_name}_pkg")
    lines.append("")

    # Also generate a usage comment
    lines.append("/*")
    lines.append(" * RTL INFERENCE PSEUDOCODE")
    lines.append(" * ========================")
    lines.append(" * Input: signed [WEIGHT_BITS-1:0] feat [0:INPUT_DIM-1]  (pre-scaled by WEIGHT_SCALE)")
    lines.append(" *")
    lines.append(" * Layer 0 (9->128):")
    lines.append(" *   for i in 0..127:")
    lines.append(" *     acc = L0_B[i]")
    lines.append(" *     for j in 0..8:")
    lines.append(" *       acc += L0_W[i*9+j] * feat[j]")
    lines.append(" *     acc >>= log2(WEIGHT_SCALE)   // re-normalize")
    lines.append(" *     h0[i] = (acc > 0) ? acc : 0  // ReLU")
    lines.append(" *")
    lines.append(" * Layer 1 (128->128): same pattern with L1_W, L1_B, h0->h1")
    lines.append(" * Layer 2 (128->64):  same pattern with L2_W, L2_B, h1->h2")
    lines.append(" *")
    lines.append(" * Output (64->3):")
    lines.append(" *   for i in 0..2:")
    lines.append(" *     logit[i] = L3_B[i]")
    lines.append(" *     for j in 0..63:")
    lines.append(" *       logit[i] += L3_W[i*64+j] * h2[j]")
    lines.append(" *     logit[i] >>= log2(WEIGHT_SCALE)")
    lines.append(" *")
    lines.append(" * Decision: action = argmax(logit[0], logit[1], logit[2])")
    lines.append(" *   0=HOLD, 1=BUY, 2=SELL")
    lines.append(" */")

    return "\n".join(lines)


def generate_python_verifier(state: dict, scale: int) -> str:
    """Generate a Python snippet to verify quantized inference matches float inference."""
    lines = []
    lines.append("# " + "="*60)
    lines.append("# QUANTIZED INFERENCE VERIFIER")
    lines.append("# Run this to check quantized weights match the original model")
    lines.append("# " + "="*60)
    lines.append("import numpy as np")
    lines.append("")
    lines.append(f"SCALE = {scale}")
    lines.append("")
    lines.append("def relu(x): return np.maximum(0, x)")
    lines.append("")
    lines.append("def infer_float(feat, state):")
    lines.append("    x = np.array(feat, dtype=np.float32)")
    lines.append("    x = relu(state['net.0.weight'] @ x + state['net.0.bias'])")
    lines.append("    x = relu(state['net.2.weight'] @ x + state['net.2.bias'])")
    lines.append("    x = relu(state['net.4.weight'] @ x + state['net.4.bias'])")
    lines.append("    x =      state['net.6.weight'] @ x + state['net.6.bias']")
    lines.append("    return x  # logits [HOLD, BUY, SELL]")
    lines.append("")
    lines.append("def infer_quantized(feat, state, scale):")
    lines.append("    def quant(arr): return np.round(arr * scale).astype(np.int32)")
    lines.append("    def relu_int(x): return np.maximum(0, x)")
    lines.append("    x = np.round(np.array(feat) * scale).astype(np.int32)")
    lines.append("    x = relu_int((quant(state['net.0.weight']) @ x) // scale + quant(state['net.0.bias']))")
    lines.append("    x = relu_int((quant(state['net.2.weight']) @ x) // scale + quant(state['net.2.bias']))")
    lines.append("    x = relu_int((quant(state['net.4.weight']) @ x) // scale + quant(state['net.4.bias']))")
    lines.append("    x =          (quant(state['net.6.weight']) @ x) // scale + quant(state['net.6.bias'])")
    lines.append("    return x  # integer logits")
    lines.append("")
    lines.append("# Test with a sample feature vector")
    lines.append("# [deviation, spread, mid_delta, ema_delta, position_norm, regime_norm,")
    lines.append("#  dev_spread_ratio, entry_price_delta, holding_time_norm]")
    lines.append("test_feat = [0.5, 0.1, -0.2, 0.0, 0.0, 0.667, 2.0, 0.0, 0.0]  # volatile, large deviation")
    lines.append("")
    lines.append("import torch")
    lines.append("ckpt = torch.load('profit_nn_out/model_best_v1_profitable.pth.tar', map_location='cpu')")
    lines.append("state = {k: v.numpy() for k, v in ckpt['state_dict'].items()}")
    lines.append("")
    lines.append("float_logits = infer_float(test_feat, state)")
    lines.append("int_logits   = infer_quantized(test_feat, state, SCALE)")
    lines.append("")
    lines.append("print('Float  logits:', float_logits)")
    lines.append("print('Quant  logits:', int_logits / SCALE)")
    lines.append("print('Float  action:', ['HOLD','BUY','SELL'][np.argmax(float_logits)])")
    lines.append("print('Quant  action:', ['HOLD','BUY','SELL'][np.argmax(int_logits)])")
    lines.append("print('Match:', np.argmax(float_logits) == np.argmax(int_logits))")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Export ProfitPolicyNet weights to SystemVerilog")
    parser.add_argument("--checkpoint", default="profit_nn_out/model_best_v1_profitable.pth.tar",
                        help="path to checkpoint .pth.tar file")
    parser.add_argument("--out", default="policy_weights.sv",
                        help="output SystemVerilog file")
    parser.add_argument("--verifier-out", default="verify_weights.py",
                        help="output Python verifier script")
    parser.add_argument("--scale", default=256, type=int,
                        help="fixed-point scale factor (default 256 = 2^8)")
    parser.add_argument("--bits", default=16, type=int,
                        help="bit width for quantized weights (default 16)")
    parser.add_argument("--module-name", default="policy_net",
                        help="SystemVerilog package/module name prefix")
    args = parser.parse_args()

    print(f"Loading checkpoint: {args.checkpoint}")
    state = load_state_dict(args.checkpoint)

    print(f"Layers found: {list(state.keys())}")
    print(f"Quantizing to {args.bits}-bit signed, scale={args.scale}")

    # weight stats
    total_params = sum(v.size for v in state.values())
    print(f"Total parameters: {total_params:,}")

    sv_code = generate_sv(state, args.scale, args.bits, args.module_name)
    with open(args.out, "w") as f:
        f.write(sv_code)
    print(f"SystemVerilog written to: {args.out}")

    verifier = generate_python_verifier(state, args.scale)
    with open(args.verifier_out, "w") as f:
        f.write(verifier)
    print(f"Python verifier written to: {args.verifier_out}")

    # quick stats on quantization error
    print("\nQuantization error summary:")
    for key, arr in state.items():
        q = np.round(arr * args.scale).astype(np.int32) / args.scale
        err = np.abs(arr - q)
        print(f"  {key:30s} shape={str(arr.shape):15s} max_err={err.max():.6f} mean_err={err.mean():.6f}")


if __name__ == "__main__":
    main()