// ============================================================================
// Testbench: tb_feature_compute
// Tests the feature_compute module: mid/spread computation, EMA update,
// first-sample initialization, deviation calculation, and pipeline delay.
//
// Golden model reference: feature_compute_vectors.json generated by
// gen_test_vectors.py (board_a seed=0xDEADBEEF, 4 symbols, CALM, alpha=6554).
// ============================================================================

`timescale 1ns / 1ps

import hft_pkg::*;

module tb_feature_compute;

    localparam int TB_NUM_SYM = 4;
    localparam int PIPELINE_DELAY = 3;

    logic                   clk;
    logic                   rst_n;
    logic                   clear;
    price_t                 bid_price;
    price_t                 ask_price;
    symbol_t                symbol_id;
    logic                   book_valid;
    logic [ALPHA_W-1:0]     ema_alpha;

    price_t                 mid;
    price_t                 spread;
    price_t                 ema;
    sprice_t                deviation;
    price_t                 bid_out;
    price_t                 ask_out;
    symbol_t                symbol_out;
    logic                   feature_valid;

    initial clk = 0;
    always #5 clk = ~clk;

    initial begin
        rst_n = 0;
        #100;
        rst_n = 1;
    end

    feature_compute #(
        .NUM_SYM(TB_NUM_SYM)
    ) dut (
        .clk          (clk),
        .rst_n        (rst_n),
        .clear        (clear),
        .bid_price    (bid_price),
        .ask_price    (ask_price),
        .symbol_id    (symbol_id),
        .book_valid   (book_valid),
        .ema_alpha    (ema_alpha),
        .mid          (mid),
        .spread       (spread),
        .ema          (ema),
        .deviation    (deviation),
        .bid_out      (bid_out),
        .ask_out      (ask_out),
        .symbol_out   (symbol_out),
        .feature_valid(feature_valid)
    );

    // ── Check task ──────────────────────────────────────────────
    integer pass_count = 0;
    integer fail_count = 0;

    task automatic check(input string name, input logic condition);
        if (condition) begin
            pass_count++;
        end else begin
            fail_count++;
            $display("[FAIL] %0s at time %0t", name, $time);
        end
    endtask

    task automatic check32(input string name, input logic [31:0] actual, input logic [31:0] expected);
        if (actual == expected) begin
            pass_count++;
        end else begin
            fail_count++;
            $display("[FAIL] %0s: got 0x%08X, expected 0x%08X at time %0t",
                     name, actual, expected, $time);
        end
    endtask

    // ── Helper: send one quote and wait for output ──────────────
    task automatic send_quote(
        input price_t  bid,
        input price_t  ask,
        input symbol_t sym
    );
        bid_price  = bid;
        ask_price  = ask;
        symbol_id  = sym;
        book_valid = 1'b1;
        @(posedge clk);
        book_valid = 1'b0;
        // Wait for pipeline (3 cycles total from input to output)
        repeat (PIPELINE_DELAY - 1) @(posedge clk);
    endtask

    // ── Test sequence ───────────────────────────────────────────
    initial begin
        bid_price  = '0;
        ask_price  = '0;
        symbol_id  = '0;
        book_valid = 1'b0;
        clear      = 1'b0;
        ema_alpha  = 16'd6554;  // ~10% smoothing, matches golden model

        @(posedge rst_n);
        repeat (2) @(posedge clk);

        // ────────────────────────────────────────────────────────
        // TEST 1: First sample for each symbol (EMA = mid, deviation = 0)
        // Golden model values from feature_compute_vectors.json
        // ────────────────────────────────────────────────────────
        $display("\n=== TEST 1: First-sample initialization ===");

        // Cycle 0: sym=0, bid=0x00B3F81E, ask=0x00B4081E → mid=0x00B4001E
        send_quote(32'h00B3F81E, 32'h00B4081E, 8'd0);
        @(posedge clk);
        check("T1.0: feature_valid",       feature_valid == 1'b1);
        check32("T1.0: mid",               mid, 32'h00B4001E);
        check32("T1.0: ema==mid (first)",   ema, 32'h00B4001E);
        check32("T1.0: deviation==0",       deviation, 32'h00000000);
        check32("T1.0: bid passthrough",    bid_out, 32'h00B3F81E);
        check32("T1.0: ask passthrough",    ask_out, 32'h00B4081E);
        check("T1.0: symbol_out==0",        symbol_out == 8'd0);

        // Cycle 1: sym=1, bid=0x01A3F821, ask=0x01A40821 → mid=0x01A40021
        send_quote(32'h01A3F821, 32'h01A40821, 8'd1);
        @(posedge clk);
        check("T1.1: feature_valid",       feature_valid == 1'b1);
        check32("T1.1: mid",               mid, 32'h01A40021);
        check32("T1.1: ema==mid (first)",   ema, 32'h01A40021);
        check32("T1.1: deviation==0",       deviation, 32'h00000000);

        // Cycle 2: sym=2, bid=0x0383F816, ask=0x03840816 → mid=0x03840016
        send_quote(32'h0383F816, 32'h03840816, 8'd2);
        @(posedge clk);
        check("T1.2: feature_valid",       feature_valid == 1'b1);
        check32("T1.2: mid",               mid, 32'h03840016);
        check32("T1.2: ema==mid (first)",   ema, 32'h03840016);
        check32("T1.2: deviation==0",       deviation, 32'h00000000);

        // Cycle 3: sym=3, bid=0x0072F81D, ask=0x0073081D → mid=0x0073001D
        send_quote(32'h0072F81D, 32'h0073081D, 8'd3);
        @(posedge clk);
        check("T1.3: feature_valid",       feature_valid == 1'b1);
        check32("T1.3: mid",               mid, 32'h0073001D);
        check32("T1.3: ema==mid (first)",   ema, 32'h0073001D);
        check32("T1.3: deviation==0",       deviation, 32'h00000000);

        // ────────────────────────────────────────────────────────
        // TEST 2: Second sample — EMA formula kicks in
        // Golden model: cycle 4, sym=0
        //   mid=0x00B40031, ema=0x00B4001F, deviation=0x00000012 (+18)
        // ────────────────────────────────────────────────────────
        $display("\n=== TEST 2: EMA computation (second sample) ===");

        // Cycle 4: sym=0
        send_quote(32'h00B3F831, 32'h00B40831, 8'd0);
        @(posedge clk);
        check("T2.0: feature_valid",       feature_valid == 1'b1);
        check32("T2.0: mid",               mid, 32'h00B40031);
        check32("T2.0: ema",               ema, 32'h00B4001F);
        check32("T2.0: deviation",          deviation, 32'h00000012);

        // Cycle 5: sym=1 → mid=0x01A40016, ema=0x01A4001F, dev=0xFFFFFFF7 (-9)
        send_quote(32'h01A3F816, 32'h01A40816, 8'd1);
        @(posedge clk);
        check32("T2.1: mid",               mid, 32'h01A40016);
        check32("T2.1: ema",               ema, 32'h01A4001F);
        check32("T2.1: deviation (-9)",     deviation, 32'hFFFFFFF7);

        // Cycle 6: sym=2 → mid=0x03840025, ema=0x03840017, dev=0x0000000E (+14)
        send_quote(32'h0383F825, 32'h03840825, 8'd2);
        @(posedge clk);
        check32("T2.2: mid",               mid, 32'h03840025);
        check32("T2.2: ema",               ema, 32'h03840017);
        check32("T2.2: deviation (+14)",    deviation, 32'h0000000E);

        // Cycle 7: sym=3 → mid=0x0073002E, ema=0x0073001E, dev=0x00000010 (+16)
        send_quote(32'h0072F82E, 32'h0073082E, 8'd3);
        @(posedge clk);
        check32("T2.3: mid",               mid, 32'h0073002E);
        check32("T2.3: ema",               ema, 32'h0073001E);
        check32("T2.3: deviation (+16)",    deviation, 32'h00000010);

        // ────────────────────────────────────────────────────────
        // TEST 3: Third round — accumulating EMA
        // Cycle 8: sym=0 → mid=0x00B4001A, ema=0x00B4001E, dev=0xFFFFFFFC (-4)
        // ────────────────────────────────────────────────────────
        $display("\n=== TEST 3: Third round EMA ===");

        send_quote(32'h00B3F81A, 32'h00B4081A, 8'd0);
        @(posedge clk);
        check32("T3.0: mid",               mid, 32'h00B4001A);
        check32("T3.0: ema",               ema, 32'h00B4001E);
        check32("T3.0: deviation (-4)",     deviation, 32'hFFFFFFFC);

        // Cycle 9: sym=1 → mid=0x01A40018, ema=0x01A4001E, dev=0xFFFFFFFA (-6)
        send_quote(32'h01A3F818, 32'h01A40818, 8'd1);
        @(posedge clk);
        check32("T3.1: mid",               mid, 32'h01A40018);
        check32("T3.1: ema",               ema, 32'h01A4001E);
        check32("T3.1: deviation (-6)",     deviation, 32'hFFFFFFFA);

        // Cycle 10: sym=2 → mid=0x0384001B, ema=0x03840017, dev=0x00000004 (+4)
        send_quote(32'h0383F81B, 32'h0384081B, 8'd2);
        @(posedge clk);
        check32("T3.2: mid",               mid, 32'h0384001B);
        check32("T3.2: ema",               ema, 32'h03840017);
        check32("T3.2: deviation (+4)",     deviation, 32'h00000004);

        // Cycle 11: sym=3 → mid=0x0073000D, ema=0x0073001C, dev=0xFFFFFFF1 (-15)
        send_quote(32'h0072F80D, 32'h0073080D, 8'd3);
        @(posedge clk);
        check32("T3.3: mid",               mid, 32'h0073000D);
        check32("T3.3: ema",               ema, 32'h0073001C);
        check32("T3.3: deviation (-15)",    deviation, 32'hFFFFFFF1);

        // ────────────────────────────────────────────────────────
        // TEST 4: Clear resets EMA state
        // After clear, next sample should seed EMA = mid again.
        // ────────────────────────────────────────────────────────
        $display("\n=== TEST 4: Clear resets EMA state ===");
        clear = 1'b1;
        @(posedge clk);
        clear = 1'b0;
        @(posedge clk);

        // Send same sym=0 values — should re-seed (deviation = 0)
        send_quote(32'h00B3F81A, 32'h00B4081A, 8'd0);
        @(posedge clk);
        check("T4: feature_valid",         feature_valid == 1'b1);
        check32("T4: ema re-seeded",        ema, 32'h00B4001A);
        check32("T4: deviation==0",          deviation, 32'h00000000);

        // ────────────────────────────────────────────────────────
        // TEST 5: Spread computation
        // ────────────────────────────────────────────────────────
        $display("\n=== TEST 5: Spread computation ===");
        // bid=0x00B3F81E, ask=0x00B4081E → spread = 0x00001000 ($0.0625)
        send_quote(32'h00B3F81E, 32'h00B4081E, 8'd1);
        @(posedge clk);
        check32("T5: spread",               spread, 32'h00001000);

        // ────────────────────────────────────────────────────────
        // TEST 6: No valid → no output
        // ────────────────────────────────────────────────────────
        $display("\n=== TEST 6: Idle ===");
        book_valid = 1'b0;
        repeat (5) @(posedge clk);
        check("T6: feature_valid==0",       feature_valid == 1'b0);

        // ────────────────────────────────────────────────────────
        // SUMMARY
        // ────────────────────────────────────────────────────────
        repeat (3) @(posedge clk);
        $display("\n══════════════════════════════════════════");
        $display("  feature_compute testbench complete");
        $display("  PASSED: %0d", pass_count);
        $display("  FAILED: %0d", fail_count);
        $display("══════════════════════════════════════════\n");

        if (fail_count > 0) $fatal(1, "TESTBENCH FAILED");
        $finish;
    end

endmodule
