// ============================================================================
// Testbench: tb_latency_histogram
// Tests the latency_histogram module: latency computation, bin mapping,
// min/max/sum/count tracking, and clear behavior.
//
// Golden model reference: latency_histogram_vectors.json generated by
// gen_test_vectors.py. All expected values are exact golden model outputs.
// ============================================================================

`timescale 1ns / 1ps

import hft_pkg::*;

module tb_latency_histogram;

    logic        clk, rst_n, clear;
    logic        fill_processed;
    timestamp_t  ts_echo;
    timestamp_t  cycle_counter;

    logic [HIST_BIN_W-1:0] hist_bins [HIST_BINS];
    logic [COUNTER_W-1:0]  lat_min, lat_max, lat_sum, lat_count;

    initial clk = 0;
    always #5 clk = ~clk;

    initial begin
        rst_n = 0;
        #100;
        rst_n = 1;
    end

    logic [COUNTER_W-1:0] last_latency;   // B3: most-recent sample (wired to silence TFMPC warning)

    latency_histogram dut (
        .clk            (clk),
        .rst_n          (rst_n),
        .clear          (clear),
        .fill_processed (fill_processed),
        .ts_echo        (ts_echo),
        .cycle_counter  (cycle_counter),
        .hist_bins      (hist_bins),
        .lat_min        (lat_min),
        .lat_max        (lat_max),
        .lat_sum        (lat_sum),
        .lat_count      (lat_count),
        .last_latency   (last_latency)               // B3
    );

    integer pass_count = 0;
    integer fail_count = 0;

    task automatic check(input string name, input logic condition);
        if (condition) begin
            pass_count++;
        end else begin
            fail_count++;
            $display("[FAIL] %0s at time %0t", name, $time);
        end
    endtask

    task automatic record_latency(
        input logic [15:0] ts,
        input logic [15:0] cyc
    );
        ts_echo        = ts;
        cycle_counter  = cyc;
        fill_processed = 1'b1;
        @(posedge clk); #1;
        fill_processed = 1'b0;
        @(posedge clk); #1;
    endtask

    initial begin
        fill_processed = 1'b0;
        ts_echo        = '0;
        cycle_counter  = '0;
        clear          = 1'b0;

        @(posedge rst_n);
        repeat (2) @(posedge clk); #1;

        // All test values from golden model latency_histogram_vectors.json:
        // (ts_echo, current_cycle) → latency, bin_idx, min, max, sum, count

        // ── GM Sample 0: ts=10, cyc=50 → lat=40, bin=1 ─────────
        $display("\n=== GM Sample 0: lat=40 ===");
        record_latency(16'd10, 16'd50);
        check("S0: bin[1]==1",    hist_bins[1] == 32'd1);
        check("S0: lat_min==40",  lat_min == 32'd40);
        check("S0: lat_max==40",  lat_max == 32'd40);
        check("S0: lat_sum==40",  lat_sum == 32'd40);
        check("S0: lat_count==1", lat_count == 32'd1);

        // ── GM Sample 1: ts=100, cyc=164 → lat=64, bin=2 ───────
        $display("\n=== GM Sample 1: lat=64 ===");
        record_latency(16'd100, 16'd164);
        check("S1: bin[2]==1",     hist_bins[2] == 32'd1);
        check("S1: lat_min==40",   lat_min == 32'd40);
        check("S1: lat_max==64",   lat_max == 32'd64);
        check("S1: lat_sum==104",  lat_sum == 32'd104);
        check("S1: lat_count==2",  lat_count == 32'd2);

        // ── GM Sample 2: ts=200, cyc=205 → lat=5, bin=0 ────────
        $display("\n=== GM Sample 2: lat=5 ===");
        record_latency(16'd200, 16'd205);
        check("S2: bin[0]==1",     hist_bins[0] == 32'd1);
        check("S2: lat_min==5",    lat_min == 32'd5);
        check("S2: lat_max==64",   lat_max == 32'd64);
        check("S2: lat_sum==109",  lat_sum == 32'd109);
        check("S2: lat_count==3",  lat_count == 32'd3);

        // ── GM Sample 3: ts=300, cyc=332 → lat=32, bin=1 ───────
        $display("\n=== GM Sample 3: lat=32 ===");
        record_latency(16'd300, 16'd332);
        check("S3: bin[1]==2",     hist_bins[1] == 32'd2);
        check("S3: lat_min==5",    lat_min == 32'd5);
        check("S3: lat_sum==141",  lat_sum == 32'd141);
        check("S3: lat_count==4",  lat_count == 32'd4);

        // ── GM Sample 4: ts=400, cyc=496 → lat=96, bin=3 ───────
        $display("\n=== GM Sample 4: lat=96 ===");
        record_latency(16'd400, 16'd496);
        check("S4: bin[3]==1",     hist_bins[3] == 32'd1);
        check("S4: lat_max==96",   lat_max == 32'd96);
        check("S4: lat_sum==237",  lat_sum == 32'd237);
        check("S4: lat_count==5",  lat_count == 32'd5);

        // ── GM Sample 5: ts=500, cyc=531 → lat=31, bin=0 ───────
        $display("\n=== GM Sample 5: lat=31 ===");
        record_latency(16'd500, 16'd531);
        check("S5: bin[0]==2",     hist_bins[0] == 32'd2);
        check("S5: lat_min==5",    lat_min == 32'd5);
        check("S5: lat_sum==268",  lat_sum == 32'd268);
        check("S5: lat_count==6",  lat_count == 32'd6);

        // ── GM Sample 6: ts=600, cyc=600 → lat=0, bin=0 ────────
        $display("\n=== GM Sample 6: lat=0 ===");
        record_latency(16'd600, 16'd600);
        check("S6: bin[0]==3",     hist_bins[0] == 32'd3);
        check("S6: lat_min==0",    lat_min == 32'd0);
        check("S6: lat_max==96",   lat_max == 32'd96);
        check("S6: lat_sum==268",  lat_sum == 32'd268);
        check("S6: lat_count==7",  lat_count == 32'd7);

        // ── GM Sample 7: ts=700, cyc=763 → lat=63, bin=1 ───────
        $display("\n=== GM Sample 7: lat=63 ===");
        record_latency(16'd700, 16'd763);
        check("S7: bin[1]==3",     hist_bins[1] == 32'd3);
        check("S7: lat_sum==331",  lat_sum == 32'd331);
        check("S7: lat_count==8",  lat_count == 32'd8);

        // ── T8: Clear ───────────────────────────────────────────
        $display("\n=== T8: Clear ===");
        clear = 1'b1;
        @(posedge clk); #1;
        clear = 1'b0;
        @(posedge clk); #1;
        check("T8: lat_count==0", lat_count == 32'd0);
        check("T8: lat_sum==0",   lat_sum == 32'd0);
        check("T8: lat_max==0",   lat_max == 32'd0);
        check("T8: lat_min reset", lat_min == 32'hFFFF_FFFF);
        check("T8: bin[0]==0",     hist_bins[0] == 32'd0);
        check("T8: bin[1]==0",     hist_bins[1] == 32'd0);

        // ── T9: No fill → no update ────────────────────────────
        $display("\n=== T9: Idle ===");
        fill_processed = 1'b0;
        cycle_counter  = 16'd999;
        ts_echo        = 16'd0;
        repeat (3) @(posedge clk); #1;
        check("T9: lat_count still 0", lat_count == 32'd0);

        // ── T10: Large latency → clamped to bin 15 ───────────
        $display("\n=== T10: Large latency (bin overflow) ===");
        // latency = 600 → bin = 600 >> 5 = 18, clamped to 15
        record_latency(16'd100, 16'd700);
        check("T10: bin[15]>=1",     hist_bins[15] >= 32'd1);
        check("T10: lat_max==600",   lat_max == 32'd600);

        // latency = 1000 → bin = 31, clamped to 15
        record_latency(16'd0, 16'd1000);
        check("T10b: bin[15]>=2",    hist_bins[15] >= 32'd2);
        check("T10b: lat_max==1000", lat_max == 32'd1000);

        // ── T11: 16-bit wrap-around (cycle < ts_echo) ────────
        $display("\n=== T11: 16-bit timestamp wrap ===");
        clear = 1'b1;
        @(posedge clk); #1;
        clear = 1'b0;
        @(posedge clk); #1;

        // ts_echo=65530, cycle=10 → latency = 10 - 65530 (mod 65536) = 16
        record_latency(16'd65530, 16'd10);
        // 16-bit subtraction: 10 - 65530 = 10 + 6 = 16 (wrapping unsigned)
        check("T11: lat wraps to 16",  lat_min == 32'd16);
        check("T11: lat_count==1",     lat_count == 32'd1);
        // bin = 16 >> 5 = 0
        check("T11: bin[0]==1",         hist_bins[0] == 32'd1);

        // ts_echo=65500, cycle=100 → latency = 100 - 65500 = 136 (wrapping)
        record_latency(16'd65500, 16'd100);
        check("T11b: lat=136",         lat_max == 32'd136);
        // bin = 136 >> 5 = 4
        check("T11b: bin[4]==1",        hist_bins[4] == 32'd1);

        // ── T12: Exact zero latency ──────────────────────────
        $display("\n=== T12: Zero latency ===");
        clear = 1'b1;
        @(posedge clk); #1;
        clear = 1'b0;
        @(posedge clk); #1;

        record_latency(16'd500, 16'd500);
        check("T12: lat==0",           lat_min == 32'd0);
        check("T12: bin[0]==1",         hist_bins[0] == 32'd1);
        check("T12: lat_sum==0",        lat_sum == 32'd0);

        // ── Summary ─────────────────────────────────────────────
        repeat (3) @(posedge clk); #1;
        $display("\n══════════════════════════════════════════");
        $display("  latency_histogram testbench complete");
        $display("  PASSED: %0d", pass_count);
        $display("  FAILED: %0d", fail_count);
        $display("══════════════════════════════════════════\n");

        if (fail_count > 0) $fatal(1, "TESTBENCH FAILED");
        $finish;
    end

endmodule
