// ============================================================================
// Testbench: tb_position_tracker
// Tests the position_tracker module: fill processing, position/cash update,
// rejected fill handling, and clear behavior.
//
// Golden model reference: position_tracker_vectors.json generated by
// gen_test_vectors.py. All expected values are exact golden model outputs.
// ============================================================================

`timescale 1ns / 1ps

import hft_pkg::*;

module tb_position_tracker;

    localparam int TB_NUM_SYM = 4;

    logic        clk, rst_n, clear;
    logic [FRAME_W-1:0] fill_frame;
    logic        fill_valid;
    position_t   position [TB_NUM_SYM];
    cash_t       cash;
    sprice_t     total_pnl;
    timestamp_t  ts_echo;
    logic        fill_processed;
    symbol_t     fill_symbol_out;
    logic        fill_side_out;
    qty_t        fill_qty_out;
    logic        fill_notify;
    logic [COUNTER_W-1:0] fills_rcvd;

    initial clk = 0;
    always #5 clk = ~clk;

    initial begin
        rst_n = 0;
        #100;
        rst_n = 1;
    end

    position_tracker #(.NUM_SYM(TB_NUM_SYM)) dut (
        .clk             (clk),
        .rst_n           (rst_n),
        .clear           (clear),
        .fill_frame      (fill_frame),
        .fill_valid      (fill_valid),
        .position        (position),
        .cash            (cash),
        .total_pnl       (total_pnl),
        .ts_echo         (ts_echo),
        .fill_processed  (fill_processed),
        .fill_symbol_out (fill_symbol_out),
        .fill_side_out   (fill_side_out),
        .fill_qty_out    (fill_qty_out),
        .fill_notify     (fill_notify),
        .fills_rcvd      (fills_rcvd)
    );

    integer pass_count = 0;
    integer fail_count = 0;

    task automatic check(input string name, input logic condition);
        if (condition) begin
            pass_count++;
        end else begin
            fail_count++;
            $display("[FAIL] %0s at time %0t", name, $time);
        end
    endtask

    task automatic check32(input string name, input logic [31:0] actual, input logic [31:0] expected);
        if (actual == expected) begin
            pass_count++;
        end else begin
            fail_count++;
            $display("[FAIL] %0s: got 0x%08X, expected 0x%08X at time %0t",
                     name, actual, expected, $time);
        end
    endtask

    task automatic check48(input string name, input logic [47:0] actual, input logic [47:0] expected);
        if (actual == expected) begin
            pass_count++;
        end else begin
            fail_count++;
            $display("[FAIL] %0s: got 0x%012X, expected 0x%012X at time %0t",
                     name, actual, expected, $time);
        end
    endtask

    initial begin
        fill_frame = '0;
        fill_valid = 1'b0;
        clear      = 1'b0;

        @(posedge rst_n);
        repeat (2) @(posedge clk);

        // ── GM Step 0: BUY sym=0, price=0x00B40CCC, qty=100 ────
        // Expected: position[0]=0x64, cash=0xFFFFB9AB0050, pnl=-18005
        $display("\n=== GM Step 0: BUY sym=0 ===");
        fill_frame = 128'h300000B40CCC00640000000A00000000;
        fill_valid = 1'b1;
        @(posedge clk);
        fill_valid = 1'b0;
        @(posedge clk);

        check("S0: fill_processed",        fill_processed == 1'b1);
        check32("S0: position[0]=0x64",     position[0], 32'h00000064);
        check48("S0: cash",                 cash, 48'hFFFFB9AB0050);
        check32("S0: total_pnl",            total_pnl, 32'hFFFFB9AB);
        check("S0: fills_rcvd==1",          fills_rcvd == 32'd1);

        // ── GM Step 1: SELL sym=1, price=0x01A41999, qty=50 ─────
        // Expected: position[1]=0xFFFFFFCE (-50), cash=0x00000BB80032, pnl=3000
        $display("\n=== GM Step 1: SELL sym=1 ===");
        fill_frame = 128'h301801A4199900320001001400000000;
        fill_valid = 1'b1;
        @(posedge clk);
        fill_valid = 1'b0;
        @(posedge clk);

        check("S1: fill_processed",        fill_processed == 1'b1);
        check32("S1: position[1]=0xFFFFFFCE", position[1], 32'hFFFFFFCE);
        check48("S1: cash",                 cash, 48'h00000BB80032);
        check("S1: fills_rcvd==2",          fills_rcvd == 32'd2);

        // ── GM Step 2: SELL sym=0, price=0x00B50000, qty=100 ────
        // Expected: position[0]=0x00000000 (back to 0), cash=0x0000526C0032, pnl=21100
        $display("\n=== GM Step 2: SELL sym=0 ===");
        fill_frame = 128'h300800B5000000640002001E00000000;
        fill_valid = 1'b1;
        @(posedge clk);
        fill_valid = 1'b0;
        @(posedge clk);

        check("S2: fill_processed",        fill_processed == 1'b1);
        check32("S2: position[0]=0",        position[0], 32'h00000000);
        check48("S2: cash",                 cash, 48'h0000526C0032);
        check("S2: fills_rcvd==3",          fills_rcvd == 32'd3);

        // ── GM Step 3: REJECTED BUY sym=2 — no position/cash change ──
        $display("\n=== GM Step 3: REJECTED ===");
        fill_frame = 128'h30210000000000000003002800000000;
        fill_valid = 1'b1;
        @(posedge clk);
        fill_valid = 1'b0;
        @(posedge clk);

        check("S3: NOT processed (reject)", fill_processed == 1'b0);
        check("S3: fill_notify (pending clear)", fill_notify == 1'b1);
        check32("S3: position[2] unchanged", position[2], 32'h00000000);
        check48("S3: cash unchanged",       cash, 48'h0000526C0032);
        check("S3: fills_rcvd still 3",     fills_rcvd == 32'd3);

        // ── GM Step 4: BUY sym=0, price=0x00B38000, qty=200 ─────
        // Expected: position[0]=0xC8 (200), cash=0xFFFFC6300032, pnl=-14800
        $display("\n=== GM Step 4: BUY sym=0, qty=200 ===");
        fill_frame = 128'h300000B3800000C80004003200000000;
        fill_valid = 1'b1;
        @(posedge clk);
        fill_valid = 1'b0;
        @(posedge clk);

        check("S4: fill_processed",        fill_processed == 1'b1);
        check32("S4: position[0]=0xC8",     position[0], 32'h000000C8);
        check48("S4: cash",                 cash, 48'hFFFFC6300032);
        check("S4: fills_rcvd==4",          fills_rcvd == 32'd4);

        // ── T5: Clear resets everything ─────────────────────────
        $display("\n=== T5: Clear ===");
        clear = 1'b1;
        @(posedge clk);
        clear = 1'b0;
        @(posedge clk);

        check32("T5: position[0] cleared",  position[0], 32'h0);
        check32("T5: position[1] cleared",  position[1], 32'h0);
        check48("T5: cash cleared",         cash, 48'h0);
        check("T5: fills_rcvd cleared",     fills_rcvd == 32'd0);

        // ── T6: ts_echo extraction ──────────────────────────────
        $display("\n=== T6: ts_echo extraction ===");
        // BUY sym=0 with ts_echo = 0x00AA
        fill_frame = {4'h3, 8'd0, 1'b0, 3'b000,
                      32'h00B4_0000, 16'd50, 16'd99, 16'h00AA, 32'h0};
        fill_valid = 1'b1;
        @(posedge clk);
        fill_valid = 1'b0;
        @(posedge clk);

        check("T6: ts_echo==0x00AA",       ts_echo == 16'h00AA);
        check("T6: fill_processed",        fill_processed == 1'b1);

        // ── Summary ─────────────────────────────────────────────
        repeat (3) @(posedge clk);
        $display("\n══════════════════════════════════════════");
        $display("  position_tracker testbench complete");
        $display("  PASSED: %0d", pass_count);
        $display("  FAILED: %0d", fail_count);
        $display("══════════════════════════════════════════\n");

        if (fail_count > 0) $fatal(1, "TESTBENCH FAILED");
        $finish;
    end

endmodule
