// ============================================================================
// Testbench: tb_strategy_engine
// Tests the strategy_engine module: mean-reversion deviation comparison,
// BUY/SELL signal generation, boundary conditions, and idle behavior.
//
// Golden model reference: strategy_vectors.json generated by
// gen_test_vectors.py (threshold=$0.50 = 0x00008000, qty=100).
// ============================================================================

`timescale 1ns / 1ps

import hft_pkg::*;

module tb_strategy_engine;

    logic        clk;
    logic        rst_n;
    sprice_t     deviation;
    price_t      bid_price;
    price_t      ask_price;
    symbol_t     symbol_id;
    logic        feature_valid;
    price_t      threshold;
    qty_t        base_qty;
    logic        signal_valid;
    logic        signal_side;
    price_t      signal_price;
    qty_t        signal_qty;
    symbol_t     signal_symbol;

    initial clk = 0;
    always #5 clk = ~clk;

    initial begin
        rst_n = 0;
        #100;
        rst_n = 1;
    end

    strategy_engine dut (
        .clk            (clk),
        .rst_n          (rst_n),
        .deviation      (deviation),
        .bid_price      (bid_price),
        .ask_price      (ask_price),
        .symbol_id      (symbol_id),
        .feature_valid  (feature_valid),
        .threshold      (threshold),
        .base_qty       (base_qty),
        .signal_valid   (signal_valid),
        .signal_side    (signal_side),
        .signal_price   (signal_price),
        .signal_qty     (signal_qty),
        .signal_symbol  (signal_symbol)
    );

    integer pass_count = 0;
    integer fail_count = 0;

    task automatic check(input string name, input logic condition);
        if (condition) begin
            pass_count++;
        end else begin
            fail_count++;
            $display("[FAIL] %0s at time %0t", name, $time);
        end
    endtask

    task automatic send_and_wait(
        input sprice_t dev,
        input price_t  bid,
        input price_t  ask,
        input symbol_t sym
    );
        deviation     = dev;
        bid_price     = bid;
        ask_price     = ask;
        symbol_id     = sym;
        feature_valid = 1'b1;
        @(posedge clk);
        feature_valid = 1'b0;
        @(posedge clk);
    endtask

    initial begin
        deviation     = '0;
        bid_price     = '0;
        ask_price     = '0;
        symbol_id     = '0;
        feature_valid = 1'b0;
        threshold     = 32'h00008000;  // $0.50 in Q16.16
        base_qty      = 16'd100;

        @(posedge rst_n);
        repeat (2) @(posedge clk);

        // ── GM Test: no deviation → no trade ────────────────────
        $display("\n=== T1: Zero deviation ===");
        send_and_wait(32'h00000000, 32'h00B40000, 32'h00B41999, 8'd0);
        check("T1: no trade", signal_valid == 1'b0);

        // ── GM Test: small positive → no trade ──────────────────
        $display("\n=== T2: Small positive deviation ===");
        send_and_wait(32'h00004CCC, 32'h00B40000, 32'h00B41999, 8'd0);
        check("T2: no trade", signal_valid == 1'b0);

        // ── GM Test: above threshold → SELL at bid ──────────────
        $display("\n=== T3: Above threshold → SELL ===");
        send_and_wait(32'h0000828F, 32'h00B40000, 32'h00B41999, 8'd2);
        check("T3: valid",         signal_valid == 1'b1);
        check("T3: side==SELL",    signal_side == 1'b1);
        check("T3: price==bid",    signal_price == 32'h00B40000);
        check("T3: qty==100",      signal_qty == 16'd100);
        check("T3: symbol==2",     signal_symbol == 8'd2);

        // ── GM Test: large positive → SELL at bid ───────────────
        $display("\n=== T4: Large positive → SELL ===");
        send_and_wait(32'h00010000, 32'h00B40000, 32'h00B41999, 8'd5);
        check("T4: valid",         signal_valid == 1'b1);
        check("T4: side==SELL",    signal_side == 1'b1);
        check("T4: price==bid",    signal_price == 32'h00B40000);

        // ── GM Test: small negative → no trade ──────────────────
        $display("\n=== T5: Small negative ===");
        send_and_wait(32'hFFFFB334, 32'h00B40000, 32'h00B41999, 8'd0);
        check("T5: no trade", signal_valid == 1'b0);

        // ── GM Test: below -threshold → BUY at ask ──────────────
        $display("\n=== T6: Below -threshold → BUY ===");
        send_and_wait(32'hFFFF7D71, 32'h00B40000, 32'h00B41999, 8'd3);
        check("T6: valid",         signal_valid == 1'b1);
        check("T6: side==BUY",     signal_side == 1'b0);
        check("T6: price==ask",    signal_price == 32'h00B41999);
        check("T6: qty==100",      signal_qty == 16'd100);
        check("T6: symbol==3",     signal_symbol == 8'd3);

        // ── GM Test: large negative → BUY at ask ────────────────
        $display("\n=== T7: Large negative → BUY ===");
        send_and_wait(32'hFFFE0000, 32'h00B40000, 32'h00B41999, 8'd0);
        check("T7: valid",         signal_valid == 1'b1);
        check("T7: side==BUY",     signal_side == 1'b0);
        check("T7: price==ask",    signal_price == 32'h00B41999);

        // ── GM Test: exactly at +threshold → NO trade ───────────
        $display("\n=== T8: Exactly at +threshold ===");
        send_and_wait(32'h00008000, 32'h00B40000, 32'h00B41999, 8'd0);
        check("T8: no trade (boundary)", signal_valid == 1'b0);

        // ── GM Test: exactly at -threshold → NO trade ───────────
        $display("\n=== T9: Exactly at -threshold ===");
        send_and_wait(32'hFFFF8000, 32'h00B40000, 32'h00B41999, 8'd0);
        check("T9: no trade (boundary)", signal_valid == 1'b0);

        // ── No valid input → no output ──────────────────────────
        $display("\n=== T10: Idle ===");
        deviation     = 32'h00010000;
        feature_valid = 1'b0;
        @(posedge clk);
        @(posedge clk);
        check("T10: no spurious valid", signal_valid == 1'b0);

        // ── Summary ─────────────────────────────────────────────
        repeat (3) @(posedge clk);
        $display("\n══════════════════════════════════════════");
        $display("  strategy_engine testbench complete");
        $display("  PASSED: %0d", pass_count);
        $display("  FAILED: %0d", fail_count);
        $display("══════════════════════════════════════════\n");

        if (fail_count > 0) $fatal(1, "TESTBENCH FAILED");
        $finish;
    end

endmodule
